# Whether or not you want to check for updates.
check-update: true
# Should players be able to use commands in game? (mctag.bypass to bypass this)
block-commands: true
# How many players should be required until the game starts?
minimum-players: 4
# Countdown time, in seconds
countdown-time: 20
# Safe period time, in seconds
safe-period-time: 5
# Match duration, in seconds
match-duration: 60
# Run in debug mode?
debug-mode: false